services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - online_learning_platform_net
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 15s
      timeout: 20s
      retries: 10
      start_period: 60s

  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
    environment:
      CONSUL_HTTP_ADDR: "http://0.0.0.0:8500"
      CONSUL_BIND_INTERFACE: "eth0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  consul-client:
    image: hashicorp/consul:latest
    container_name: consul-client
    command: "agent -client=0.0.0.0 -retry-join=consul-server"
    depends_on:
      - consul-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/peers"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  postgres-auth:
    image: postgres:15-alpine
    container_name: postgres-auth
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AUTH_DB_USERNAME} -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USERNAME} -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  postgres-courses:
    image: postgres:15-alpine
    container_name: postgres-courses
    environment:
      POSTGRES_DB: course_db
      POSTGRES_USER: ${COURSE_DB_USERNAME}
      POSTGRES_PASSWORD: ${COURSE_DB_PASSWORD}
    volumes:
      - postgres_courses_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${COURSE_DB_USERNAME} -d course_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  postgres-lessons:
    image: postgres:15-alpine
    container_name: postgres-lessons
    environment:
      POSTGRES_DB: lesson_db
      POSTGRES_USER: ${LESSON_DB_USERNAME}
      POSTGRES_PASSWORD: ${LESSON_DB_PASSWORD}
    volumes:
      - postgres_lessons_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LESSON_DB_USERNAME} -d lesson_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net
  
  postgres-enrollments:
    image: postgres:15-alpine
    container_name: postgres-enrollments
    environment:
      POSTGRES_DB: enrollment_db
      POSTGRES_USER: ${ENROLLMENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ENROLLMENT_DB_PASSWORD}
    volumes:
      - postgres_enrollments_data:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ENROLLMENT_DB_USERNAME} -d enrollment_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  postgres-assignments:
    image: postgres:15-alpine
    container_name: postgres-assignments
    environment:
      POSTGRES_DB: assignment_db
      POSTGRES_USER: ${ASSIGNMENT_DB_USERNAME}
      POSTGRES_PASSWORD: ${ASSIGNMENT_DB_PASSWORD}
    volumes:
      - postgres_assignments_data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ASSIGNMENT_DB_USERNAME} -d assignment_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  postgres-submissions:
    image: postgres:15-alpine
    container_name: postgres-submissions
    environment:
      POSTGRES_DB: submission_db
      POSTGRES_USER: ${SUBMISSION_DB_USERNAME}
      POSTGRES_PASSWORD: ${SUBMISSION_DB_PASSWORD}
    volumes:
      - postgres_submissions_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SUBMISSION_DB_USERNAME} -d submission_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  redis-auth:
    image: redis:7-alpine
    container_name: redis-auth
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net
      

  redis-users:
    image: redis:7-alpine
    container_name: redis-users
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net
  

  redis-courses:
    image: redis:7-alpine
    container_name: redis-courses
    ports:
      - "6381:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  redis-lessons:
    image: redis:7-alpine
    container_name: redis-lessons
    ports:
      - "6382:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  redis-enrollments:
    image: redis:7-alpine
    container_name: redis-enrollments
    ports:
      - "6383:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  redis-assignments:
    image: redis:7-alpine
    container_name: redis-assignments
    ports:
      - "6384:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  redis-submissions:
    image: redis:7-alpine
    container_name: redis-submissions
    ports:
      - "6385:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${ASSIGNMENT_MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${ASSIGNMENT_MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  config-server:
    build: 
      context: ../backend/config-server
    environment:
       - GIT_USERNAME=${GIT_USERNAME}
       - GIT_PASSWORD=${GIT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 90s
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  gateway-service:
    build:
      context: ../backend/gateway-service
    environment:
    - SPRING_PROFILES_ACTIVE=dev
    - JWT_SECRET=${JWT_SECRET}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8080/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      consul-client:
        condition: service_started
    restart: unless-stopped
    networks:
      - online_learning_platform_net
    

  auth-service:
    build:
      context: ../backend/auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - AUTH_DB_URL=${AUTH_DB_URL}
      - AUTH_DB_USERNAME=${AUTH_DB_USERNAME}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_REDIS_HOST=${AUTH_REDIS_HOST}
    volumes:
      - ../backend/auth-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8081/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-auth:
        condition: service_healthy
      postgres-auth:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  user-service:
    build:
      context: ../backend/user-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - USER_DB_URL=${USER_DB_URL}
      - USER_DB_USERNAME=${USER_DB_USERNAME}
      - USER_DB_PASSWORD=${USER_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - USER_REDIS_HOST=${USER_REDIS_HOST}
    volumes:
      - ../backend/user-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8082/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-users:
        condition: service_healthy
      postgres-users:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net
      

  course-service:
    build:
      context: ../backend/course-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - COURSE_DB_URL=${COURSE_DB_URL}
      - COURSE_DB_USERNAME=${COURSE_DB_USERNAME}
      - COURSE_DB_PASSWORD=${COURSE_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - COURSE_REDIS_HOST=${COURSE_REDIS_HOST}
    volumes:
      - ../backend/course-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8083/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-courses:
        condition: service_healthy
      postgres-courses:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net

  
  lesson-service:
    build:
      context: ../backend/lesson-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - LESSON_DB_URL=${LESSON_DB_URL}
      - LESSON_DB_USERNAME=${LESSON_DB_USERNAME}
      - LESSON_DB_PASSWORD=${LESSON_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - LESSON_REDIS_HOST=${LESSON_REDIS_HOST}
    volumes:
      - ../backend/lesson-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8084/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-lessons:
        condition: service_healthy
      postgres-lessons:
        condition: service_healthy
    networks:
      - online_learning_platform_net


  enrollment-service:
    build:
      context: ../backend/enrollment-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ENROLLMENT_DB_URL=${ENROLLMENT_DB_URL}
      - ENROLLMENT_DB_USERNAME=${ENROLLMENT_DB_USERNAME}
      - ENROLLMENT_DB_PASSWORD=${ENROLLMENT_DB_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - ENROLLMENT_REDIS_HOST=${ENROLLMENT_REDIS_HOST}
    volumes:
      - ../backend/enrollment-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8085/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-enrollments:
        condition: service_healthy
      postgres-enrollments:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  notification-service:
    build:
      context: ../backend/notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8086/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
    restart: unless-stopped
    networks:
      - online_learning_platform_net


  assignment-service:
    build:
      context: ../backend/assignment-service
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - ASSIGNMENT_DB_URL=${ASSIGNMENT_DB_URL}
      - ASSIGNMENT_DB_USERNAME=${ASSIGNMENT_DB_USERNAME}
      - ASSIGNMENT_DB_PASSWORD=${ASSIGNMENT_DB_PASSWORD}
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ASSIGNMENT_REDIS_HOST=${ASSIGNMENT_REDIS_HOST}
      - ASSIGNMENT_MINIO_URL=${ASSIGNMENT_MINIO_URL}
      - ASSIGNMENT_MINIO_ACCESS_KEY=${ASSIGNMENT_MINIO_ACCESS_KEY}
      - ASSIGNMENT_MINIO_SECRET_KEY=${ASSIGNMENT_MINIO_SECRET_KEY}
      - ASSIGNMENT_MINIO_BUCKET_NAME=${ASSIGNMENT_MINIO_BUCKET_NAME}
    volumes:
      - ../backend/assignment-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8087/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-assignments:
        condition: service_healthy
      postgres-assignments:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net
  

  submission-service:
    build:
      context: ../backend/submission-service
    environment:
      - SUBMISSION_DB_URL=${SUBMISSION_DB_URL}
      - SUBMISSION_DB_USERNAME=${SUBMISSION_DB_USERNAME}
      - SUBMISSION_DB_PASSWORD=${SUBMISSION_DB_PASSWORD}
      - SPRING_FLYWAY_ENABLED=true
      - SPRING_FLYWAY_LOCATIONS=classpath:/db/migration
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SUBMISSION_REDIS_HOST=${SUBMISSION_REDIS_HOST}
      - SUBMISSION_MINIO_URL=${SUBMISSION_MINIO_URL}
      - SUBMISSION_MINIO_ACCESS_KEY=${SUBMISSION_MINIO_ACCESS_KEY}
      - SUBMISSION_MINIO_SECRET_KEY=${SUBMISSION_MINIO_SECRET_KEY}
      - SUBMISSION_MINIO_BUCKET_NAME=${SUBMISSION_MINIO_BUCKET_NAME}
    volumes:
      - ../backend/submission-service/src/main/resources/db/migration:/app/resources/db/migration
    healthcheck:
      test: ["CMD", "curl", "-s", "http://localhost:8088/internal/actuator/health"]
      interval: 15s
      timeout: 5s
      start_period: 60s
    depends_on:
      config-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      consul-server:
        condition: service_started
      redis-submissions:
        condition: service_healthy
      postgres-submissions:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net
    

  frontend:
    build: 
      context: ../frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      gateway-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy
      course-service:
        condition: service_healthy
      lesson-service:
        condition: service_healthy
      enrollment-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      assignment-service:
        condition: service_healthy
      submission-service:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - online_learning_platform_net


volumes:
  consul-data:
  minio-data:

  postgres_auth_data:
  postgres_users_data:
  postgres_courses_data:
  postgres_lessons_data:
  postgres_enrollments_data:
  postgres_assignments_data:
  postgres_submissions_data:


networks:
  online_learning_platform_net:
    driver: bridge